-- AlterTable
ALTER TABLE "Celebrity" ADD COLUMN "bio" TEXT;
ALTER TABLE "Celebrity" ADD COLUMN "featured" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Celebrity" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
